export const FETCHED_NUMBER = 'FETCHED_NUMBER';
export const REQUEST_CHECK = 'REQUEST_CHECK';
// export const CHECK_NUMBER = 'CHECK_NUMBER';
export const CHECK_NUMBER_SUCCEEDED = 'CHECK_NUMBER_SUCCEEDED';
export const CHECK_NUMBER_FAILED = 'CHECK_NUMBER_FAILED';
